services:
  web-api-v2:
    build:
      context: .
      dockerfile: docker/api/web-api-v2/Dockerfile
    image: spidercontrol/web-api-v2:1.0.0
    ports:
      - "8080:80"
      - "8443:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80

  angular-js:
    build:
      context: .
      dockerfile: docker/frontend/angular-js/Dockerfile
    image: spidercontrol/angular-js:1.0.0
    ports:
      - "4200:80"
    depends_on:
      - web-api-v2
