services:
  web-api-v2:
    build:
      context: .
      dockerfile: docker/api/web-api-v2/Dockerfile
    image: spidey-senses/web-api-v2:local
    ports:
      - "8080:80"
      - "8443:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=K8sLocal
      - ASPNETCORE_URLS=http://+:80

  angular-js:
    build:
      context: .
      dockerfile: docker/frontend/angular-js/Dockerfile
      args:
        - ANGULAR_ENV=k8s-local
    image: spidey-senses/angular-js:local
    ports:
      - "4200:80"
    depends_on:
      - web-api-v2
