apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# - web-api-deployment.yaml
# - web-api-service.yaml
# - angular-deployment.yaml
# - angular-service.yaml
# - ingress.yaml
- namespace.yaml