apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/api
  - ingress.yaml
  - configmap.yaml

patches:
- path: deployment.yaml
  target:
    kind: Deployment
    name: api

images:
  - name: ghcr.io/war/spidey-senses/web-api-v2
