apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/frontend
  - ingress.yaml

patches:
- path: deployment.yaml
  target:
    kind: Deployment
    name: frontend

images:
  - name: ghcr.io/war/spidey-senses/angular-js
    newName: spidey-senses/angular-js
    newTag: local