apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: api
        envFrom:
        - configMapRef:
            name: spidey-senses-api-config