apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/api

images:
  - name: ghcr.io/war/spidey-senses/web-api-v2
    newName: spidey-senses/web-api-v2
    newTag: local

configMapGenerator:
  - name: api-config
    literals:
      - ASPNETCORE_ENVIRONMENT=Development