name: API CI Pipeline

on:
  push:
    branches: [ main, develop, feature/**, bugfix/** ]
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/**'

jobs:
  # Build Web API v2
  build-webapiv2:
    uses: ./.github/workflows/reusable-api-build.yml
    with:
      service-name: webapiv2
      project-path: src/api/SpiderControl.WebApiV2/SpiderControl.WebApiV2.csproj
  
  # Test Web API v2
  test-webapiv2:
    needs: build-webapiv2
    uses: ./.github/workflows/reusable-api-test.yml
    with:
      service-name: webapiv2
      test-project-path: tests/SpiderControl.WebApiV2.Tests/SpiderControl.WebApiV2.Tests.csproj
  
  # Build Web API v2 Docker Image & Push
  docker-webapiv2:
    needs: test-webapiv2
    uses: ./.github/workflows/reusable-docker-build.yml
    with:
      service-name: webapiv2
      dockerfile-path: docker/api/web-api-v2/Dockerfile

  # Coverage Report
  coverage-report:
    needs: [test-webapiv2]
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/reusable-coverage-report.yml
    with:
      coverage-artifacts: webapiv2-coverage
