name: API CI Pipeline

on:
  push:
    branches: [main, develop, feature/*]
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/**'

jobs:
  # Build Web API v2
  build-web-api-v2:
    uses: ./.github/workflows/reusable-api-build.yml
    with:
      service-name: web-api-v2
      project-path: src/api/SpiderControl.WebApiV2/SpiderControl.WebApiV2.csproj
  
  # Test Web API v2
  test-web-api-v2:
    needs: build-web-api-v2
    uses: ./.github/workflows/reusable-api-test.yml
    with:
      service-name: web-api-v2
      test-project-path: tests/SpiderControl.WebApiV2.Tests/SpiderControl.WebApiV2.Tests.csproj
  
  # Build Web API v2 Docker Image & Push
  docker-web-api-v2:
    needs: test-web-api-v2
    uses: ./.github/workflows/reusable-docker-build.yml
    with:
      service-name: web-api-v2
      dockerfile-path: docker/api/web-api-v2/Dockerfile
