name: Backend CI/CD Pipeline

on:
  push:
    branches: [ develop, feature/**, bugfix/** ]
  pull_request:
    branches: [ main, develop, release/** ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    
    - name: Restore dependencies
      run: dotnet restore src/api/SpiderControl.WebApiV2/SpiderControl.WebApiV2.csproj
    
    - name: Build
      run: dotnet build src/api/SpiderControl.WebApiV2/SpiderControl.WebApiV2.csproj --no-restore --configuration Release
    
    - name: Run unit tests
      run: dotnet test tests/SpiderControl.WebApiV2.Tests/ --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage
    
    - name: Upload coverage reports
      uses: codecov/codecov-action@v5
      with:
        directory: ./coverage
        fail_ci_if_error: false
    
  build-docker:
    needs: build-and-test
    runs-on: ubuntu-latest
    outputs:
      image_url: ${{ steps.short-sha.outputs.image_url }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/${{ github.repository }}/backend
        tags: |
          type=ref,event=branch
          type=sha,format=short
          type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
          
    - name: Extract full docker repo url
      id: short-sha
      run: |
        IMAGE_URL=$(echo "${{ steps.meta.outputs.tags }}" | grep "sha-" | head -n 1)
        echo "image_url=$IMAGE_URL" >> $GITHUB_OUTPUT
    
    - name: Build and push Docker image
      id: build-and-push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: docker/api/web-api-v2/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
  test-container:
    needs: build-docker
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Pull Docker image
      run: docker pull ${{ needs.build-docker.outputs.image_url }}
    
    - name: Run container tests
      run: |
        docker run --name api-test -d -p 8080:80 ${{ needs.build-docker.outputs.image_url }}
        sleep 5
        curl -sSf http://localhost:8080/health || exit 1
        docker logs api-test
