name: Frontend CI/CD Pipeline

run-name: Frontend CI/CD - ${{ github.event.head_commit.message }}

on:
  push:
    branches: [ develop, feature/**, bugfix/** ]
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        cache: 'npm'
        cache-dependency-path: src/frontend/spider-control-web/package-lock.json
    
    - name: Install dependencies
      working-directory: src/frontend/spider-control-web/
      run: npm ci
    
    # - name: Lint
    #   working-directory: src/frontend/spider-control-web/
    #   run: npm run lint
    
    - name: Build
      working-directory: src/frontend/spider-control-web/
      run: npm run build --if-present
    
    # - name: Test
    #   working-directory: src/frontend/spider-control-web/
    #   run: npm test -- --no-watch --no-progress --browsers=ChromeHeadless
    
  build-docker:
    needs: build-and-test
    runs-on: ubuntu-latest
    outputs:
      image_url: ${{ steps.short-sha.outputs.image_url }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/${{ github.repository }}/frontend
        tags: |
          type=ref,event=branch
          type=sha,format=short
          type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}

    - name: Extract full docker repo url
      id: short-sha
      run: |
        IMAGE_URL=$(echo "${{ steps.meta.outputs.tags }}" | grep "sha-" | head -n 1)
        echo "image_url=$IMAGE_URL" >> $GITHUB_OUTPUT

    - name: Build and push Docker image
      id: build-and-push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: docker/frontend/angular/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
  test-container:
    needs: build-docker
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Pull Docker image
      run: docker pull ${{ needs.build-docker.outputs.image_url }}
    
    - name: Run container tests
      run: |
        docker run --name frontend-test -d -p 4200:80 ${{ needs.build-docker.outputs.image_url }}
        sleep 5
        curl -sSf http://localhost:4200/ || exit 1
        docker logs frontend-test
