name: Frontend CI Pipeline

on:
  push:
    branches: [main, develop, feature/*]
    paths:
      - 'src/frontend/**'
      - 'tests/**'
      - '.github/**'

jobs:
  # Angular UI
  build-angular-ui:
    uses: ./.github/workflows/reusable-nodejs-build.yml
    with:
      service-name: angular-ui
      working-directory: src/frontend/spider-control-web
  
  # test-angular-ui:
  #   needs: build-angular-ui
  #   uses: ./.github/workflows/reusable-nodejs-test.yml
  #   with:
  #     service-name: angular-ui
  #     working-directory: src/frontend/spider-control-web
  
  # Build Angular UI Docker Image
  docker-angular-ui:
    needs: build-angular-ui
    uses: ./.github/workflows/reusable-docker-build.yml
    with:
      service-name: angular-ui
      dockerfile-path: docker/frontend/angular/Dockerfile
