name: Frontend CI Pipeline

on:
  push:
    branches: [main, develop, feature/*]
    paths:
      - 'src/frontend/**'
      - 'tests/**'
      - '.github/**'

jobs:
  # Angular UI
  build-angular-js:
    uses: ./.github/workflows/reusable-nodejs-build.yml
    with:
      service-name: angular-js
      working-directory: src/frontend/angular-js
  
  # test-angular-js:
  #   needs: build-angular-js
  #   uses: ./.github/workflows/reusable-nodejs-test.yml
  #   with:
  #     service-name: angular-js
  #     working-directory: src/frontend/angular-js
  
  # Build Angular UI Docker Image
  docker-angular-js:
    needs: build-angular-js
    uses: ./.github/workflows/reusable-docker-build.yml
    with:
      service-name: angular-js
      dockerfile-path: docker/frontend/angular-js/Dockerfile
