name: PR Coverage Report

on:
  workflow_run:
    workflows: ["API CI Pipeline"]
    types:
      - completed
    branches:
      - 'feature/*'
      - 'main'
      - 'develop'

jobs:
  # Generate combined coverage report
  generate-combined-report:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'pull_request' }}
    uses: ./.github/workflows/reusable-coverage-report.yml
    with:
      coverage-artifacts: "*-coverage-data"
      report-title: "SpiderControl PR Coverage Report"
      deploy-to-pages: true
      comment-on-pr: true

  # Add check that fails if coverage is below threshold
  coverage-check:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'pull_request' }}
    needs: generate-combined-report
    runs-on: ubuntu-latest
    steps:
      - name: Check coverage threshold
        run: |
          COVERAGE="${{ needs.generate-combined-report.outputs.coverage-percentage }}"
          THRESHOLD=80.0
          
          if (( $(echo "$COVERAGE < $THRESHOLD" | bc -l) )); then
            echo "::error::Coverage ($COVERAGE%) is below the threshold ($THRESHOLD%)"
            exit 1
          else
            echo "Coverage ($COVERAGE%) meets the threshold ($THRESHOLD%)"
          fi