name: PR Coverage Report

on:
  pull_request:
    branches: [main, develop, feature/**]
    types:
      - opened
      - closed
      - synchronize
      - reopened

jobs:
  # Generate combined coverage report
  generate-combined-report:
    uses: ./.github/workflows/reusable-coverage-report.yml
    with:
      coverage-artifacts: "*-coverage-data"
      report-title: "SpiderControl PR Coverage Report"
      deploy-to-pages: true
      comment-on-pr: true
    secrets:
      REPORTGENERATOR_LICENSE: ${{ secrets.REPORTGENERATOR_LICENSE }}
