name: Reusable DotNet Build

on:
  workflow_call:
    inputs:
      service-name:
        required: true
        type: string
        description: "Name of the API service"
      project-path:
        required: true
        type: string
        description: "Path to the project file"
      dotnet-version:
        required: false
        type: string
        default: "9.0.x"
        description: "Version of .NET to use"
    outputs:
      build-success:
        description: "Indicates if the build was successful"
        value: ${{ jobs.build.outputs.success }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      success: ${{ steps.status.outputs.success }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet-version }}
          dotnet-quality: 'ga'
      
      - name: Restore dependencies
        run: dotnet restore ${{ inputs.project-path }}
      
      - name: Build
        run: dotnet build ${{ inputs.project-path }} --no-restore --configuration Release
      
      - name: Set output status
        id: status
        run: echo "success=true" >> $GITHUB_OUTPUT
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.service-name }}-build
          path: |
            **/bin/Release/**/*.dll
            **/bin/Release/**/*.pdb
          retention-days: 1
