name: Reusable Coverage Report

on:
  workflow_call:
    inputs:
      coverage-artifacts:
        required: true
        type: string
        description: "Comma-separated list of coverage artifact names to download"
    
jobs:
  generate-report:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Create artifacts directory
        run: mkdir -p ./coverage-reports
      
      - name: Download coverage artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./coverage-reports
          pattern: "*-coverage"
          merge-multiple: true
      
      - name: Prepare coverage report
        id: prepare-report
        run: |
          echo "# Code Coverage Summary" > coverage-summary.md
          echo "## Summary by Service" >> coverage-summary.md
          
          # Find and concatenate all summary files
          find ./coverage-reports -name "summary.md" -o -name "Summary.md" | while read file; do
            echo "" >> coverage-summary.md
            cat "$file" >> coverage-summary.md
          done
          
          echo "report-content<<EOF" >> $GITHUB_OUTPUT
          cat coverage-summary.md >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      
      - name: Add coverage PR comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          message: ${{ steps.prepare-report.outputs.report-content }}
