name: Reusable Frontend Build

on:
  workflow_call:
    inputs:
      service-name:
        required: true
        type: string
        description: "Name of the frontend service"
      working-directory:
        required: true
        type: string
        description: "Directory containing package.json"
      node-version:
        required: false
        type: string
        default: "22.x"
        description: "Version of Node.js to use"
    outputs:
      build-success:
        description: "Indicates if the build was successful"
        value: ${{ jobs.build.outputs.success }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      success: ${{ steps.status.outputs.success }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'npm'
          cache-dependency-path: ${{ inputs.working-directory }}/package-lock.json
      
      - name: Install dependencies
        working-directory: ${{ inputs.working-directory }}
        run: npm ci
      
      - name: Build
        working-directory: ${{ inputs.working-directory }}
        run: npm run build --if-present
      
      - name: Set output status
        id: status
        run: echo "success=true" >> $GITHUB_OUTPUT
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.service-name }}-build
          path: ${{ inputs.working-directory }}/dist
          retention-days: 1
