name: Reusable Coverage Report

on:
  workflow_call:
    secrets:
      REPORTGENERATOR_LICENSE:
        required: true
    inputs:
      coverage-artifacts:
        required: true
        type: string
        description: "Comma-separated list of coverage artifact names to download"
      report-title:
        required: false
        type: string
        default: "Code Coverage Report"
        description: "Title for the coverage report"
      deploy-to-pages:
        required: false
        type: boolean
        default: false
        description: "Whether to deploy the report to GitHub Pages"
      comment-on-pr:
        required: false
        type: boolean
        default: true
        description: "Whether to add a comment to the PR with the coverage summary"
    
jobs:
  generate-report:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Create artifacts directory
        run: mkdir -p ./coverage-reports
      
      - name: Download coverage artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./coverage-reports
          pattern: ${{ inputs.coverage-artifacts }}
          merge-multiple: true
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
          dotnet-quality: 'ga'
    
      - name: Test with coverage
        run: dotnet test --collect:"XPlat Code Coverage"
      
      - name: Install ReportGenerator
        run: dotnet tool install -g dotnet-reportgenerator-globaltool
      
      - name: Generate combined coverage report
        run: |
          echo "Running ReportGenerator with license parameter"
          reportgenerator \
            -reports:"**/coverage.cobertura.xml" \
            -targetdir:"./combined-coverage" \
            -reporttypes:"Html,MarkdownSummary,JsonSummary,Badges" \
            -title:"${{ inputs.report-title }}" \
            -license:"${{ secrets.REPORTGENERATOR_LICENSE }}"
      
      - name: Add coverage PR comment
        if: inputs.comment-on-pr && github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          path: ./combined-coverage/Summary.md
      
      - name: Upload combined coverage report
        uses: actions/upload-artifact@v4
        with:
          name: combined-coverage-report
          path: ./combined-coverage
          retention-days: 14
      
      - name: Deploy to GitHub Pages
        if: inputs.deploy-to-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./combined-coverage

      - name: Copy badge to gh-pages
        run: |
          mkdir -p badge
          cp ./combined-coverage/badge_shieldsio_methodcoverage_blue.svg badge/coverage.svg
        
      - name: Upload badge to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./badge
