name: Deploy API Documentation

on:
  pull_request:
    branches: [main, develop, feature/**]
    types:
    - opened
    - closed
    - synchronize
    - reopened

jobs:
  generate-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      
      - name: Restore dependencies
        run: |
          dotnet restore tests/SpiderControl.WebApiV2.Tests
      
      - name: Run OpenAPI export test
        run: |
          dotnet test tests/SpiderControl.WebApiV2.Tests --filter "FullyQualifiedName=SpiderControl.WebApiV2.Tests.OpenApiExportTests.ExportOpenApiDocument_ShouldGenerateValidJson"
      
      - name: Create output directory
        run: mkdir -p api-docs
        
      - name: Copy OpenAPI document
        run: |
          cp tests/SpiderControl.WebApiV2.Tests/bin/Debug/net9.0/openapi-output/openapi.json api-docs/
        
      - name: Create simple UI
        run: |
          cat > api-docs/index.html << 'EOF'
          <!DOCTYPE html>
          <html>
            <head>
              <title>Spider Control API Documentation</title>
              <meta http-equiv="refresh" content="0;URL='https://war.github.io/spidey-senses/api-docs/openapi.json'" />
            </head>
            <body>
              <p>Redirecting to <a href="https://war.github.io/spidey-senses/api-docs/openapi.json">Swagger UI</a>...</p>
            </body>
          </html>
          EOF
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
