name: Deploy API Documentation

on:
  pull_request:
    branches: [main, develop, feature/**]
    types:
    - opened
    - closed
    - synchronize
    - reopened

jobs:
  generate-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      
      - name: Restore dependencies
        run: |
          dotnet restore tests/SpiderControl.WebApiV2.Tests
      
      - name: Run OpenAPI export test
        run: |
          dotnet test tests/SpiderControl.WebApiV2.Tests --filter "FullyQualifiedName=SpiderControl.WebApiV2.Tests.OpenApiExportTests.ExportOpenApiDocument_ShouldGenerateValidJson"
      
      - name: Create output directory
        run: mkdir -p api-docs
        
      - name: Copy OpenAPI document
        run: |
          cp tests/SpiderControl.WebApiV2.Tests/bin/Debug/net9.0/openapi-output/openapi.json api-docs/
      
      - name: Create Swagger UI
        run: |
          cat > api-docs/index.html << 'EOF'
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8">
            <title>Spider Control API Documentation</title>
            <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/swagger-ui-dist@5.11.8/swagger-ui.css">
            <link rel="icon" type="image/png" href="https://cdn.jsdelivr.net/npm/swagger-ui-dist@5.11.8/favicon-32x32.png" sizes="32x32" />
            <link rel="icon" type="image/png" href="https://cdn.jsdelivr.net/npm/swagger-ui-dist@5.11.8/favicon-16x16.png" sizes="16x16" />
            <style>
              html { box-sizing: border-box; overflow: -moz-scrollbars-vertical; overflow-y: scroll; }
              *, *:before, *:after { box-sizing: inherit; }
              body { margin: 0; background: #fafafa; }
              .swagger-ui .topbar { background-color: #000; }
              .swagger-ui .info { margin: 20px 0; }
              .swagger-ui .info hgroup.main h2 { font-size: 2em; }
              .swagger-ui .info hgroup.main { margin-bottom: 20px; }
            </style>
          </head>

          <body>
            <div id="swagger-ui"></div>

            <script src="https://cdn.jsdelivr.net/npm/swagger-ui-dist@5.11.8/swagger-ui-bundle.js"></script>
            <script src="https://cdn.jsdelivr.net/npm/swagger-ui-dist@5.11.8/swagger-ui-standalone-preset.js"></script>
            <script>
              window.onload = function() {
                const ui = SwaggerUIBundle({
                  url: "openapi.json",
                  dom_id: '#swagger-ui',
                  deepLinking: true,
                  presets: [
                    SwaggerUIBundle.presets.apis,
                    SwaggerUIStandalonePreset
                  ],
                  plugins: [
                    SwaggerUIBundle.plugins.DownloadUrl
                  ],
                  layout: "BaseLayout",
                  tagsSorter: "alpha",
                  filter: true,
                  displayRequestDuration: true,
                  defaultModelsExpandDepth: 3,
                  defaultModelExpandDepth: 3
                });
                window.ui = ui;
              }
            </script>
          </body>
          </html>
          EOF
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          keep_files: true